#!/bin/bash

DIR="/etc/httpd/"


userscripts_dir="/home/mo/.config/sxmo/userscripts"
myscripts_dir="/home/mo/Documents/myscripts"

if [ -d "$userscripts_dir" ]; then
  ### Take action if $DIR exists ###
  echo " $userscripts_dir exists"
else
  ###  Control will jump here if $DIR does NOT exists ###
  mkdir -p $userscripts_dir
fi

cd $myscripts_dir

cp -r userscripts/* $userscripts_dir


