#!/bin/bash

sudo apk add flatpak

sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    
sudo apk add bash xfce4-terminal xfce4-screenshooter mousepad chromium texmaker texlive-full nano ranger
